from PyQt6.QtWidgets import QDialog, QVBoxLayout, QTabWidget, QWidget, QComboBox, QDoubleSpinBox, QPushButton, QLabel

class DeleteDialog(QDialog):
    def __init__(self, groups, subjects, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Удаление записей")
        self.layout = QVBoxLayout(self)
        self.tabs = QTabWidget()

        self.tab_avg = QWidget()
        l1 = QVBoxLayout(self.tab_avg)
        self.sub_avg_combo = QComboBox()
        self.sub_avg_combo.addItems(subjects)
        self.min_avg = QDoubleSpinBox()
        self.max_avg = QDoubleSpinBox()
        for s in [self.min_avg, self.max_avg]: s.setRange(1, 10)
        self.btn_del_avg = QPushButton("Удалить по среднему баллу")
        l1.addWidget(QLabel("Предмет:"))
        l1.addWidget(self.sub_avg_combo)
        l1.addWidget(QLabel("Средний балл (от и до):"))
        l1.addWidget(self.min_avg)
        l1.addWidget(self.max_avg)
        l1.addWidget(self.btn_del_avg)

        self.tab_group = QWidget()
        l2 = QVBoxLayout(self.tab_group)
        self.group_combo = QComboBox()
        self.group_combo.addItems(groups)
        self.btn_del_group = QPushButton("Удалить по группе")
        l2.addWidget(QLabel("Выберите группу:"))
        l2.addWidget(self.group_combo)
        l2.addWidget(self.btn_del_group)

        self.tab_item = QWidget()
        l3 = QVBoxLayout(self.tab_item)
        self.sub_item_combo = QComboBox()
        self.sub_item_combo.addItems(subjects)
        self.min_item = QDoubleSpinBox()
        self.max_item = QDoubleSpinBox()
        for s in [self.min_item, self.max_item]: s.setRange(1, 10)
        self.btn_del_item = QPushButton("Удалить по баллу предмета")
        l3.addWidget(QLabel("Предмет:"))
        l3.addWidget(self.sub_item_combo)
        l3.addWidget(QLabel("Балл предмета (от и до):"))
        l3.addWidget(self.min_item)
        l3.addWidget(self.max_item)
        l3.addWidget(self.btn_del_item)

        self.tabs.addTab(self.tab_avg, "Средний балл")
        self.tabs.addTab(self.tab_group, "Группа")
        self.tabs.addTab(self.tab_item, "Балл предмета")
        self.layout.addWidget(self.tabs)